# Generated by Django 5.1.7 on 2025-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrnamentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ornament_type', models.CharField(choices=[('glasses', 'Glasses'), ('necklace', 'Necklace'), ('earrings', 'Earrings')], max_length=20)),
                ('image', models.ImageField(upload_to='ornaments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
